# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 
    commands:
      - echo Installing dependencies....
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo node version ..... 
      - node -v
      - echo running build... 
      - npm run build
      - echo ls -all ....
      - ls -all
  post_build:
    commands:
      - echo Build completed 
      - echo Pre-Build started 
      - aws s3 cp ./dist/** s3://${BUCKET_NAME} --recursive --acl public-read
      - echo Pre-Build completed on
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - dist/**
